### ISSUE TITLE
楼主 这个用不了啊

### ISSUE THREAD

**Issue by blackAzrael** [vicety/pixiv-beta#3]
2018-05-15 22:08:21 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.pixiv.net/member_illust.php?mode=medium&illust_id=68680416> (referer: https://accounts.pixiv.net/login?lang=zh&source=pc&view_type=page&ref=wwwtop_accounts_index)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 30, in process_spider_output
    for x in result:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\DEAN\Desktop\Pixiv-Crawler-master\pixiv_beta\spiders\pixiv-beta.py", line 249, in image_page
    raise UnmatchError("Unsupported gif image or not enough authority to visit the page when crawling {0}".format(response.url))

**Comment by vicety** [comment]
Pixiv网页改版导致的，已经更改了代码，应该可以用了
